### ISSUE TITLE
Data type for Images

### ISSUE THREAD

**Issue by ydallilar** [JuliaAstro/CCDReduction.jl#6]
Hi,

Data reduction becomes a daily routine for me from to time to time and I wanted to explore julia a bit. Since this is a new project, I thought I would contribute.

So, I started developing a CCDImage data type here:
https://github.com/pssncp142/CCDReduction.jl/tree/devel_CCDImage

Note that I learnt Julia last week so my code is not very clean. It will require many revisions. 

This, in a basic level, describes what it can/should do:
https://gist.github.com/pssncp142/a60e97872ac761d3a4456c0aeb9b73f6 

The question is, would you be interested in such a data type? It would allow propagation and storage of uncertainties and bad pixels, and can be stored in your image "Collection". I will work on this regardless since it helps me explore arrays and types functionality in julia. But, if you are interested, I am happy to discuss your opinions and revise the design to integrate into your project.

**Comment by mileslucas** [comment]
Based on the notebook it seems relatively close to my vision for the "CCDData" type! Although I do not plan on making a custom type for pixels, since I think we can do fine using existing numeric types with Unitful.jl and Measurements.jl.

Currently I'm working with @siddharthlal25 through Google Summer of Code (GSoC) on this package, so we have plans for implementing this later! Your implementation is a good show of using the abstract array interface and is definitely inspirational for our usage.

If you're interested in contributing, I would recommend looking around JuliaAstro for help wanted issues, I (we) have plenty of issues that we'd love a hand with that will also sharpen your Julia skills!
